# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='avmoo_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indeximg', models.CharField(max_length=999)),
                ('titileimg', models.CharField(max_length=999)),
                ('fanhao', models.CharField(max_length=100)),
                ('faxingshijian', models.CharField(max_length=100)),
                ('yingpianchangdu', models.CharField(max_length=100)),
                ('zhizaoshang', models.CharField(max_length=100)),
                ('faxingshang', models.CharField(max_length=100)),
                ('xilie', models.CharField(max_length=100)),
                ('leibie', models.CharField(max_length=100)),
                ('artists', models.CharField(max_length=100)),
                ('artistsimg', models.CharField(max_length=999)),
                ('simpleimg', models.CharField(max_length=9999)),
                ('bigsimpleimg', models.CharField(max_length=9999)),
            ],
        ),
    ]
